global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "ecommerce-streaming"
    environment: "development"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "spark-master"
    metrics_path: "/metrics/master/prometheus"
    static_configs:
      - targets: ["spark-master:8080"]
      - labels:
          role: "master"

  - job_name: "spark-worker"
    metrics_path: "/metrics/worker/prometheus"
    static_configs:
      - targets: ["spark-worker:8081"]
      - labels:
          role: "worker"
